datasets: 
    ecommerce: zh
    douban: zh
    writer: zh
    ubuntu: en

models:
    - dual-bert
    - dual-bert-gray
    - bert-ft
    - sa-bert
    - poly-encoder
    - dual-bert-hierarchical

# huge file are saved in the root dir
# root_dir: /apdcephfs/private_johntianlan/MyReDial
root_dir: /dockerdata/johntianlan/sources/MyReDial

# pjli bert model
pj:
    is_used: true
    tokenizer: /apdcephfs/share_916081/pjli/bert_zh_300g_wordpiece_base/data/vocab.txt
    pretrained_model: /apdcephfs/share_916081/pjli/bert_zh_300g_wordpiece_base/ckpt/epoch1_batch_1759999
