datasets: 
    ecommerce: zh
    douban: zh
    writer: zh
    lccc: zh
    ubuntu: en
    # inference dataset
    poetry: zh
    news_withsource: zh
    novel_selected: zh
    baike_summary: zh
    arxiv: en
    restoration-200k: zh
    essay: zh
    unlikelyhood-gen: zh
    ext_douban: zh

# pretrained model and tokenizer
tokenizer:
    # zh: hfl/chinese-roberta-wwm-ext
    zh: bert-base-chinese
    # zh: hfl/chinese-bert-wwm-ext
    en: bert-base-uncased

pretrained_model:
    # zh: hfl/chinese-roberta-wwm-ext
    zh: bert-base-chinese
    # zh: hfl/chinese-bert-wwm-ext
    en: bert-base-uncased

# the number of the gray negative samples (writer dataset)
gray_cand_num: 5
rank: null

no_test_models:
    - bert-fp
    - bert-fp-mono
    - simcse
    - bert-mask-da

no_train_models:
    - bert-fp-original
    - bert-mask-da

models:
    bert-mask-da:
        type: Augmentation
        model_name: BERTMaskAugmentationModel
        # inference_dataset_name: BERTMaskAugmentationDataset
        inference_dataset_name: BERTMaskAugmentationFullDataset
    dual-bert-ml: 
        type: Representation
        model_name: BERTDualMLEncoder
        dataset_name: BERTDualFullDataset
        inference_dataset_name: BERTDualInferenceDataset
    simcse: 
        type: PostTrain
        model_name: SimCSE
        dataset_name: SimCSEDataset
        # inference_dataset_name: BERTSimCSEInferenceDataset
        inference_dataset_name: BERTSimCSEInferenceContextDataset
    dual-bert-mixup: 
        type: Representation
        model_name: BERTDualMixUpEncoder
        dataset_name: BERTDualFullDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-semi: 
        type: Representation
        model_name: BERTDualSemiEncoder
        dataset_name: BERTDualSemiDataset
        inference_dataset_name: BERTDualInferenceDataset
        # inference_dataset_name: BERTDualInferenceContextDataset
    dual-bert-grading: 
        type: Representation
        model_name: BERTDualGradingEncoder
        dataset_name: BERTDualFullNegSessionDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-ishn: 
        type: Representation
        model_name: BERTDualISHNEncoder
        dataset_name: BERTDualFullISHNDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-cosine: 
        type: Representation
        model_name: BERTDualCosineEncoder
        dataset_name: BERTDualFullDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-hn-hier: 
        type: Representation
        model_name: BERTDualHNHierEncoder
        dataset_name: BERTDualHNDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-hn-pos:
        type: Representation
        model_name: BERTDualHNPosEncoder
        # dataset_name: BERTDualBertMaskHardNegativeWithPositionWeightDataset
        dataset_name: FineGrainedTestPositionWeightDataset
        # inference_dataset_name: BERTDualInferenceDataset
        inference_dataset_name: BERTDualInferenceFullEXTWithTestDataset
        # inference_dataset_name: BERTDualInferenceWithTestDataset
    dual-bert-hn: 
        type: Representation
        model_name: BERTDualHNEncoder
        # dataset_name: BERTDualHNDataset
        # dataset_name: BERTDualBertMaskHardNegativeDataset
        dataset_name: FineGrainedTestDataset
        # dataset_name: BERTDualFullWithHardNegDataset
        # inference_dataset_name: BERTDualInferenceDataset
        inference_dataset_name: BERTDualInferenceFullEXTWithTestDataset
        # inference_dataset_name: BERTDualInferenceWithTestDataset
    dual-bert-proj: 
        type: Representation
        model_name: BERTDualHNProjEncoder
        # dataset_name: BERTDualBertMaskHardNegativeDataset
        # inference_dataset_name: BERTDualInferenceDataset
        inference_dataset_name: BERTDualInferenceFullEXTWithTestDataset
    dual-bert-pos:
        type: Representation
        model_name: BERTDualPositionWeightEncoder
        # dataset_name: BERTDualFullWithPositionWeightDataset
        dataset_name: FineGrainedTestPositionWeightDataset
        inference_dataset_name: BERTDualInferenceFullEXTWithTestDataset
        # inference_dataset_name: BERTDualInferenceWithTestDataset
    dual-bert: 
        type: Representation
        model_name: BERTDualEncoder
        # dataset_name: BERTDualFullExtraNegDataset
        # dataset_name: BERTDualFullExtraNegFromOutDatasetDataset
        # dataset_name: BERTDualFullFakeCtxDataset
        # dataset_name: BERTDualDataset
        # dataset_name: BERTDualFullWithHardNegDataset
        dataset_name: BERTDualFullDataset
        # dataset_name: FineGrainedTestDataset
        # dataset_name: BERTDualReplaceBadResponseDataset
        # dataset_name: BERTDualFullDACTXDataset
        # dataset_name: BERTDualExtFullDataset
        # dataset_name: BERTDualFullNegSessionDataset
        # dataset_name: BERTDualFullWithSelfPlayDataset
        # dataset_name: BERTDualFullPseudoDataset
        # inference_dataset_name: BERTDualInferenceDataset
        inference_dataset_name: BERTDualInferenceWithTestDataset
        # inference_dataset_name: BERTDualInferenceFullWithTestDataset
        # inference_dataset_name: BERTDualInferenceFullEXTWithTestDataset
        # inference_dataset_name: BERTDualInferenceWithSourceDataset
        # inference_dataset_name: BERTDualInferenceFullDataset
        # inference_dataset_name: BERTDualInferenceFullEXTDataset
        # inference_dataset_name: BERTDualInferenceContextDataset
        # inference_dataset_name: BERTDualInferenceFullContextDataset
        # inference_dataset_name: BERTDualInferenceFullContextSingleExtendDataset
        # inference_dataset_name: BERTDualInferenceFullForOne2ManyDataset
    dual-bert-bow: 
        type: Representation
        model_name: BERTDualBOWEncoder
        dataset_name: BERTDualFullDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-phrase: 
        type: Generation
        model_name: BERTDualPhraseEncoder
        dataset_name: BERTDualPhraseDataset
        inference_dataset_name: BERTDualInferencePhraseDataset
    dual-bert-one2many-original: 
        type: Representation
        model_name: BERTDualO2MOriginalEncoder
        dataset_name: BERTDualO2MDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-one2many: 
        type: Representation
        model_name: BERTDualO2MEncoder
        # model_name: BERTDualO2MTopKEncoder
        dataset_name: BERTDualO2MDataset
        # dataset_name: BERTDualFullDataset
        inference_dataset_name: BERTDualInferenceDataset
        # inference_dataset_name: BERTDualInferenceFullDataset
        # inference_dataset_name: BERTDualInferenceFullEXTDataset
        # inference_dataset_name: BERTDualInferenceContextDataset
    dual-bert-fusion: 
        type: Representation
        model_name: BERTDualFusionEncoder
        dataset_name: BERTDualDataset
        inference_dataset_name: BERTDualCLInferenceDataset
    dual-bert-fusion-gray-writer: 
        type: Representation
        model_name: BERTDualFusionGrayFullEncoder
        dataset_name: BERTDualFullWithNegDataset
        inference_dataset_name: BERTDualCLInferenceDataset
    hash-bert: 
        type: Representation
        model_name: HashBERTDualEncoder
        dataset_name: BERTDualFullWithNegDataset
        # dataset_name: BERTDualDataset
        inference_dataset_name: BERTDualFullInferenceDataset
        # inference_dataset_name: BERTDualInferenceDataset
    gpt2: 
        type: Generation
        model_name: GPT2Model
        dataset_name: GPT2Dataset
        inference_dataset_name: null
    dual-bert-gen: 
        type: Generation
        model_name: BERTSeq2SeqDualEncoder
        dataset_name: BERTDualDataset
        inference_dataset_name: null
    seq2seq: 
        type: Generation
        model_name: BERTSeq2SeqEncoder
        dataset_name: BERTDualDataset
        inference_dataset_name: null 
    dual-bert-gray: 
        type: Representation
        model_name: BERTDualGrayEncoder
        dataset_name: BERTDualFullWithNegDataset
        inference_dataset_name: BERTDualInferenceDataset
    dual-bert-gray-writer: 
        type: Representation
        model_name: BERTDualGrayFullEncoder
        dataset_name: BERTDualFullWithNegDataset
        # dataset_name: BERTDualArxivDataset
        # inference_dataset_name: BERTDualFullInferenceDataset
        inference_dataset_name: BERTDualFullWithSourceInferenceDataset
    dual-bert-hierarchical: 
        type: Representation
        model_name: BERTDualHierarchicalTrsEncoder
        dataset_name: BERTDualHierarchicalDataset
        inference_dataset_name: BERTDualInferenceDataset
    bert-ft: 
        type: Interaction
        model_name: BERTRetrieval
        dataset_name: BERTFTDataset
        inference_dataset_name: null 
    bert-ft-essay: 
        type: Evaluation
        model_name: BERTEssayRetrieval
        dataset_name: BERTFTEssayDataset
        inference_dataset_name: null 
    bert-fp-original: 
        type: Interaction
        model_name: BERTFPRetrieval
        dataset_name: BERTFTDataset
        inference_dataset_name: null 
    bert-ft-compare: 
        type: CompareInteraction
        model_name: BERTCompareRetrieval
        dataset_name: BERTFTCompDataset
        # BERTFTCompEvaluationDataset used for test.sh[compare mode]
        # dataset_name: BERTFTCompEvaluationDataset
        inference_dataset_name: null
    dual-bert-comp-hn: 
        type: Representation
        model_name: BERTDualCompareHNEncoder
        # dataset_name: BERTDualFullDataset
        dataset_name: FineGrainedTestDataset
        # dataset_name: BERTDualBertMaskHardNegativeDataset
        inference_dataset_name: BERTDualInferenceFullEXTDataset
    dual-bert-comp: 
        type: Representation
        model_name: BERTDualCompareEncoder
        dataset_name: BERTDualFullDataset
        # dataset_name: FineGrainedTestDataset
        inference_dataset_name: BERTDualInferenceFullEXTDataset
    dual-bert-compare: 
        type: CompareInteraction
        model_name: BERTDualCompEncoder
        dataset_name: BERTDualWithNegDataset
        inference_dataset_name: null
    sa-bert: 
        type: Interaction
        model_name: SABERTRetrieval 
        dataset_name: SABERTFTDataset
        inference_dataset_name: null 
    poly-encoder: 
        type: LatentInteraction
        model_name: PolyEncoder
        dataset_name: BERTDualFullDataset
        inference_dataset_name: null
    bert-fp: 
        type: PostTrain
        model_name: BERTFPPostTrain
        dataset_name: PostTrainDataset
        inference_dataset_name: null 
    bert-fp-mono: 
        type: PostTrain
        model_name: BERTMonolingualPostTrain
        dataset_name: PostTrainMonoDataset
        inference_dataset_name: null 
    dual-bert-pt: 
        type: PostTrain 
        model_name: BERTDualPTEncoder
        dataset_name: BERTDualPTDataset
        # inference_dataset_name: BERTDualInferenceDataset
        inference_dataset_name: BERTDualInferenceContextDataset
    kenlm:
        type: LanguageModel
        model_name: KeNLM
        dataset_name: null
        inference_dataset_name: null
    gpt2lm:
        type: LanguageModel
        model_name: GPT2LM
        dataset_name: null
        inference_dataset_name: null

# huge file are saved in the root dir
root_dir: /apdcephfs/share_916081/johntianlan/MyReDial
# root_dir: /home/johntianlan/sources/MyReDial

# test interval: higher than 1 means that we donot test during training procedure, which is necessary for the corpus which has the big test set
# test_interval: 1.1
test_interval: 0.1


# ========== deploy parameters ========== #
deploy:
    host: '0.0.0.0'
    port: 22335
    dataset: restoration-200k
    max_len: 256
    res_max_len: 64
    recall:
        activate: false
        model: dual-bert-hn-pos
        # default topk
        topk: 100
        # only the arxiv, writer dataset need the with_source
        with_source: false
        # index_type: IVF3722,Flat
        # index_type: IVF6509,Flat
        index_type: Flat
        index_nprobe: 1
        # index_type: Flat
        dimension: 768
    rerank:
        activate: false
        model: null
    pipeline:
        activate: false
    pipeline_evaluation:
        activate: true
