# basic configuration for building the model
dropout: 0.1

# train configuration
train:
    lr: 0.00003
    grad_clip: 1.0
    seed: 0
    batch_size: 96
    max_len: 256
    min_mask_num: 1
    min_context_length: 3
    min_token_length: 20
    epoch: 25
    warmup_ratio: 0.1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false
