# basic configuration for building the model
tokenizer: 
    zh: bert-base-chinese
    en: bert-base-uncased
pretrained_model: 
    zh: bert-base-chinese
    en: bert-base-uncased
dropout: 0.1

# train configuration
train:
    lr: 0.00005
    grad_clip: 1.0
    test_interval: 0.05
    seed: 50
    batch_size: 32
    max_len: 320
    epoch: 5
    warmup_ratio: 0.1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 50
    batch_size: 32
    max_len: 320 
