test_interval: 0.1
valid_during_training: false
is_step_for_training: true
dropout: 0.1

# gpt2 configuration
gpt2_topk: 10
gpt2_topp: 0.9
gpt2_gen_max_len: 64
gpt2_gen_max_ctx_len: 128
gpt2_max_len: 128
gpt2_tokenizer: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
gpt2_pretrained_model: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/duyu_roberta
    en: /apdcephfs/share_916081/johntianlan/duyu_roberta
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/duyu_roberta
    en: /apdcephfs/share_916081/johntianlan/duyu_roberta
    
# corrupt parameters   
# from easy to hard, curriculumn learning strategy
corrupt_min_ratio: 0.0
corrupt_max_ratio: 0.0
corrupt_min_topk: 1
corrupt_max_topk: 1

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 128
    total_step: 50010
    inference_time: 1
    easy_cand_num: 1
    warmup_ratio: 0.05
    checkpoint: 
        path: bert-fp/best_bert-base-chinese.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 128
