# [inner_bsz] the batch for one train step is to big, split and run it in multiple times
# then the gradient accumulation is used
inner_bsz: 64
gray_cand_num: 2
compare_turn_num: 2
positive_margin: 0.
positive_margin_delta: 0.0
num_labels: 1
test_interval: 0.01
grad_clip: 1.0
# true for domain-specific corpus: ecommerce and ubuntu
# replace the hard negative with the random negative
no_hard_negative: false

# train configuration
train:
    lr: 0.00005
    seed: 0
    batch_size: 32
    max_len: 288    # 256 + 32
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    # must be one (because of the fully compare)
    batch_size: 1
    max_len: 288
