# basic configuration for building the model
dropout: 0.1
gray_cand_num: 10
# [inner_bsz] the batch for one train step is to big, split and run it in multiple times
inner_bsz: 48
# the number of the negative samples will be considered in each batch
k: 2
compare_turn_num: 2
rank: bert-ft-compare-plus
positive_margin: 0.
positive_margin_delta: 0.0

# train configuration
train:
    lr: 0.00005
    grad_clip: 1.0
    seed: 50
    batch_size: 16
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: true

# test configuration
test:
    seed: 50
    # must be one (because of the fully compare)
    batch_size: 1
    max_len: 256
    res_max_len: 64
