# basic configuration for building the model
dropout: 0.1
# rank: bert-ft-compare-plus
rank: null

# do not train on this checkpoint (maybe you can?)

# test configuration
test:
    seed: 0
    batch_size: 32
    max_len: 256
