rank: null
gray_cand_num: 5
temp: 1.0
fgm: false
test_interval: 0.1

# train configuration
train:
    lr: 0.00001
    grad_clip: 1.0
    seed: 0
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 1
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: dual-bert/best_bert-base-chinese.pt
        # path: dual-bert/best_bert-base-uncased.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-mono/best_bert-base-chinese.pt
        # path: simcse/best_bert-base-chinese.pt
        is_load: true

# test conf6iguration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 128 
    max_len: 64
    ctx_max_len: 256
    topk: 20
    index_type: Flat
    index_nprobe: 1
    dimension: 768
