# train configuration
train:
    lr: 0.00003
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    min_mask_num: 1
    max_mask_num: 20
    masked_lm_prob: 0.15
    min_ctx_len: 16
    min_res_len: 8
    full_turn_length: 5
    max_len: 256
    res_max_len: 64
    epoch: 35
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true
