# dual-bert with post train (dual-bert-pt)
smoothing: 0.1
# rank: bert-ft-compare
rank: null
min_mask_num: 1
max_mask_num: 20
masked_lm_prob: 0.1
min_len: 5
full_turn_length: 5

# train configuration
train:
    lr: 0.00005
    grad_clip: 1.0
    seed: 50
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 50
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 50
    batch_size: 128
    max_len: 64
    topk: 20
    index_type: LSH
    dimension: 768
