dropout: 0.1
nhead: 6
nhide: 512
nlayer: 2

# train configuration
train:
    lr: 0.00005
    grad_clip: 1.0
    smoothing: 0.1
    seed: 50
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 50
    batch_size: 1
    max_len: 256
    res_max_len: 64
    tokenizer: 
        zh: bert-base-chinese
        en: bert-base-uncased

inference:
    seed: 50
    batch_size: 128
    max_len: 64
