temp: 1.
full_turn_length: 5
test_interval: 0.05
valid_during_training: false
nhead: 8
num_layers: 1
# easy or hard additional negative samples
easy_gray: false
gray_cand_num: 2
# context-aware
context_aware_before_comparison: true
proj_hidden_size: 2048
dropout: 0.1
# add the innert context negative sample
inner_context_negative: false
use_encoder_hidden_states: true
before_comp: true

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
# max_len and res_max_len are (64,32) for RRS and E-commerce, (128, 32) for douban
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 10 
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-comp/best_bert-base-chinese.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        # path: bert-fp-mono/best_bert-base-uncased.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 32
    ctx_max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
