test_interval: 0.01
valid_during_training: false
is_step_for_training: true
total_step: 40000
seq_un_begin_step: 38500
sequence_ngram_n: 4
sample_ratio: 0.15

# gpt2 configuration
test_max_len: 128
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    max_len: 256
    un_prefix_len: 64
    un_generated_len: 64
    warmup_ratio: 0.
    iter_to_accumulate: 1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 128
    # this means the prefix length
    max_len: 256
