test_interval: 0.01
valid_during_training: false
is_step_for_training: true
total_step: 50010
test_max_len: 128 
sep_smooth_length: 50
prefix_len: 32

# gpt2 configuration
test_max_len: 128
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

# train configuration
train:
    load_param: true
    lr: 0.00002
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    max_len: 256
    warmup_ratio: 0.
    iter_to_accumulate: 8
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 128
    max_len: 256
