# basic configuration for building the model
tokenizer: 
    # zh: /apdcephfs/share_916081/johntianlan/gpt2_model
    zh: /apdcephfs/share_916081/johntianlan/uer_gpt2_model
pretrained_model: 
    # zh: /apdcephfs/share_916081/johntianlan/gpt2_model
    zh: /apdcephfs/share_916081/johntianlan/uer_gpt2_model
test_interval: 0.01
valid_during_training: false
gen_max_len: 32 
gen_max_ctx_len: 128
topk: 50
topp: 1.0
repetition_penalty: 3.0

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 128
    max_len: 128
    epoch: 20
    warmup_ratio: 0.05
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
