test_interval: 0.0001
valid_during_training: false
is_step_for_training: true
total_step: 50010
test_gen_max_len: 128
beam_width: 5
model_prediction_confidence: 0.6
sampling_probability: 0.
sep_smooth_length: 50
contrastive_topk: 8
contrastive_topp: 0.93
prefix_len: 32

# gpt2 configuration load locally
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english

# train configuration
train:
    load_param: true
    lr: 0.00002
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    max_len: 256
    warmup_ratio: 0.
    iter_to_accumulate: 8
    margin: 0.5
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
