test_interval: 0.01
valid_during_training: false
is_step_for_training: true
total_step: 50010
temp: 0.07
max_phrase_len: 10
length_penalty: 1.1
min_effective_token_len: 2

# memory
min_phrase_len: 2
max_phrase_len: 7
max_memory_size: 500000

# gpt2 configuration
test_max_len: 128
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 16
    max_len: 384
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 128
    # this means the prefix length
    max_len: 128
