test_interval: 0.01
valid_during_training: false
is_step_for_training: true
total_step: 50010
sequence_ngram_n: 4
sample_token_num: 20 
# coarse-grained topk_lower ~ topk_upper will be used as the hard negative samples for coarse-grained retrieval
cg_topk_upper: 5000
cg_topk_lower: 10
cg_alpha: 10.
# fine-grained topk_lower ~ topk_upper will be used as the hard negative samples for coarse-grained retrieval
fg_topk_upper: 100
fg_topk_lower: 50
dropout: 0.1

# gpt2 configuration
test_max_len: 128
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

bert_tokenizer: /apdcephfs/share_916081/johntianlan/duyu_roberta
bert_pretrained_model: /apdcephfs/share_916081/johntianlan/duyu_roberta

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 16
    max_len: 384
    gtd_prefix_len: 32
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 128
    # this means the prefix length
    max_len: 128
