hash_code_size: 512
hidden_size: 1024
dropout: 0.1
# 0-11 layers will be fine-tuned, other index are invalid
trainable_bert_layers: 12
q_alpha: 0.0001
q_alpha_max: 0.1
hash_loss_scale: 1
hash_head_num: 10

# train configuration
train:
    lr: 0.0005
    grad_clip: 1.0
    smoothing: 0.1
    seed: 50
    batch_size: 128
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.1
    checkpoint: 
        # path: dual-bert-gray-writer/best_bert-base-chinese.pt
        path: dual-bert/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 50
    batch_size: 1
    max_len: 256
    res_max_len: 64

inference:
    seed: 50
    batch_size: 512
    max_len: 64
    index_type: BFlat
    dimension: 512
    topk: 100
