temp: 0.07

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 256
    res_max_len: 64
    epoch: 1
    warmup_ratio: 0.05
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        is_load: false

inference:
    seed: 0
    batch_size: 128
    max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 1
    dimension: 768
