temp: 0.05
dropout: 0.3
nhead: 12
nlayer: 3
attention_span: 2
test_interval: 0.05
alpha_weight: 0.1

pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/chinese-bert-wwm-ext
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/chinese-bert-wwm-ext

# train configuration
train:
    lr: 0.00001
    grad_clip: 1.0
    seed: 0
    batch_size: 128
    max_len: 64
    epoch: 1
    warmup_ratio: 0.
    checkpoint: 
        path: wz-simcse/best_simcse.pt
        is_load: true

test:
    seed: 0
    batch_size: 128
    max_len: 128

inference:
    seed: 0
    batch_size: 512
    max_len: 128
    topk: 200
    index_type: LSH
    index_nprobe: 1
    dimension: 768
