# [inner_bsz] the batch for one train step is to big, split and run it in multiple times
inner_bsz: 64
gray_cand_num: 2
compare_turn_num: 2
positive_margin: 0.1
positive_margin_delta: 0.0
num_labels: 1
test_interval: 0.05
no_hard_negative: false
valid_during_training: true

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 384    # 320 + 32 + 32
    epoch: 5
    warmup_ratio: 0.05
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-comp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 384
