pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00003
    grad_clip: 5.0
    seed: 0
    batch_size: 48
    max_len: 328
    min_mask_num: 1
    max_mask_num: 20
    masked_lm_prob: 0.15
    min_context_length: 2
    min_token_length: 20
    epoch: 35
    dropout: 0.1
    warmup_ratio: 0.01
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp/best_bert-base-uncased.pt
        is_load: true
