# basic configuration for building the model
dropout: 0.1
ext_read: false
is_step_for_training: false
total_step: 240000
save_every: 20000

# network issue, load locally
tokenizer:
    # zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    zh: /apdcephfs/share_916081/johntianlan/chinese-roberta-wwm-ext-large
    # zh: /apdcephfs/share_916081/johntianlan/chinese-roberta-wwm-ext
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    # zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    zh: /apdcephfs/share_916081/johntianlan/chinese-roberta-wwm-ext-large
    # zh: /apdcephfs/share_916081/johntianlan/chinese-roberta-wwm-ext
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00003
    grad_clip: 1.0
    seed: 0
    batch_size: 128
    max_len: 32
    # minimum valid tokens number
    min_len: 5
    min_mask_num: 2
    max_mask_num: 10
    masked_lm_prob: 0.2
    epoch: 35
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-no-cls/best_bert-base-chinese.pt
        # path: bert-post/best_nspmlm.pt
        is_load: false
