test_interval: 0.05
valid_during_training: true
gray_cand_num_hn: 2
gray_cand_num_en: 2
dropout: 0.1
nhead: 12
num_layers: 2


# load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased


# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 64
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
