# basic configuration for building the model
rank: null
# for data augmentation
full_turn_length: 100
test_interval: 0.0001
# true for ubuntu and horse, false for douban and ecommerce
valid_during_training: false

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
# pretrained_model:
#     zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
#     en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-mono/best_bert-base-uncased.pt
        is_load: true

# test configuration
test:
    seed: 0
    # batch_size: 32
    batch_size: 1
    max_len: 256
