# [inner_bsz] the batch for one train step is to big, split and run it in multiple times
inner_bsz: 48
gray_cand_num: 2
positive_margin: 0.1
ambiguous_margin: 0.5
positive_margin_delta: 0.0
num_labels: 1
test_interval: 0.01
no_hard_negative: false
valid_during_training: false
random_sample_pool_size: 10000
is_step_for_training: true
total_step: 4000000
save_every: 100000
recall_pool_size: 256

data_root_path: /apdcephfs/share_916081/johntianlan/chatbot-large-scale-dataset-final-version
buffer_size: 409600

pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00003
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    max_len: 256
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        path: bert-fp-comp/best__apdcephfs_share_916081_johntianlan_chinese-roberta-wwm-ext_16.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 384
