# basic configuration for building the model
dropout: 0.1

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00003
    grad_clip: 1.0
    seed: 0
    batch_size: 256
    max_len: 64
    # minimum valid tokens number
    min_len: 5
    min_mask_num: 2
    max_mask_num: 10
    masked_lm_prob: 0.2
    epoch: 10
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-no-cls/best_bert-base-chinese.pt
        # path: bert-post/best_nspmlm.pt
        is_load: false 
