# basic configuration for building the model
rank: null
# for data augmentation
full_turn_length: 1
test_interval: 0.05
# true for ubuntu and horse, false for douban and ecommerce
valid_during_training: false
is_step_for_training: true
total_step: 1000010
save_every: 50000

data_root_path: /apdcephfs/share_916081/johntianlan/chatbot-large-scale-dataset-final-version
buffer_size: 409600

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_733425/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_733425/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 128
    max_len: 128
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp/best__apdcephfs_share_916081_johntianlan_bert-base-chinese_19.pt
        # path: bert-fp-mono/best_bert-base-uncased.pt
        is_load: true

# test configuration
test:
    seed: 0
    # batch_size: 32
    batch_size: 128
    max_len: 256

# for inference_clean mode
# inference clean parameters
inference:
    seed: 0
    batch_size: 512
    max_len: 128
    buff_size: 100000
    r_data_root_path: /apdcephfs/share_733425/johntianlan/chatbot-data-clean/weibo_clean
    w_data_root_path: /apdcephfs/share_733425/johntianlan/chatbot-data-clean/weibo_clean_ft_v2
