# [inner_bsz] the batch for one train step is to big, split and run it in multiple times
# inner_bsz: 64
# positive_margin: 0.1
# ambiguous_margin: 0.5
# positive_margin_delta: 0.0
# num_labels: 2
test_interval: 0.2
# no_hard_negative: false
valid_during_training: true
# random_sample_pool_size: 10000
is_step_for_training: false
# total_step: 2000000
# save_every: 100000
dropout: 0.1

# for ranking
# gray_cand_num: 2
# recall_pool_size: 1024
# rank_num: 32
# rank_score_threshold: 0.3
# rank_score_threshold_positive: 0.85

# data_root_path: /apdcephfs/share_916081/johntianlan/chatbot-large-scale-dataset-final-version
# buffer_size: 409600

pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    # en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
    # en: /apdcephfs/share_916081/johntianlan/electra-base-discriminator
    # en: /apdcephfs/share_916081/johntianlan/roberta-base
    # en: /apdcephfs/share_916081/johntianlan/bert-large-uncased
    # en: /apdcephfs/share_916081/johntianlan/electra-large-discriminator
    en: /apdcephfs/share_916081/johntianlan/roberta-large
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    # en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
    # en: /apdcephfs/share_916081/johntianlan/electra-base-discriminator
    # en: /apdcephfs/share_916081/johntianlan/roberta-base
    # en: /apdcephfs/share_916081/johntianlan/bert-large-uncased
    # en: /apdcephfs/share_916081/johntianlan/electra-large-discriminator
    en: /apdcephfs/share_916081/johntianlan/roberta-large

# train configuration
train:
    lr: 0.00001
    grad_clip: 1.0
    seed: 0
    eps: 0.000001
    batch_size: 16
    max_len: 384
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        path: bert-fp-comp/best__apdcephfs_share_916081_johntianlan_roberta-base_2.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 384
