hash_code_size: 256
test_interval: 0.05
valid_during_training: true
full_turn_length: 5
hidden_size: 1024
dropout: 0.1
beta_gamma: 0.01
mv_num: 5

pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese

# train configuration
train:
    lr: 0.001
    bert_lr: 0.00001
    grad_clip: 1.0
    smoothing: 0.1
    seed: 0
    batch_size: 128
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.0
    checkpoint: 
        path: dual-bert/best__apdcephfs_share_916081_johntianlan_bert-base-chinese_700.pt
        is_load: true

# test configuration
test:
    seed: 50
    batch_size: 1
    max_len: 256
    res_max_len: 64

inference:
    seed: 50
    batch_size: 512
    max_len: 64
    index_type: BFlat
    index_nprobe: 5
    dimension: 4096
    topk: 20
