test_interval: 0.05
gray_cand_num: 5
valid_during_training: true
temp: 0.05

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
# pretrained_model:
#     zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
#     en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-comp/best_bert-base-chinese.pt
        # path: bert-fp-multi/best_bert-base-chinese.pt
        # path: dual-bert-pt/best_bert-base-chinese.pt
        # path: bert-fp-no-cls/best_bert-base-chinese.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        # path: bert-fp-mono/best_bert-base-uncased.pt
        # path: simcse/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 32
    ctx_max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
