test_max_len: 128
prefix_len: 32
doc_max_length: 256
max_doc_num: 10
min_phrase_length: 3
max_phrase_length: 16
max_doc_length: 256
# the topk phrases that be considered
search_topk: 10
threshold: 20.
recall_topk: 50
# the max seqlength for calculating the phrase ppl
max_rerank_len: 128
phrase_alpha: 1.
# dynamic update the docs
update_step: 32
test_max_len: 128

phrase_tokenizer: /apdcephfs/share_916081/johntianlan/bert-base-chinese
phrase_encoder_model: /apdcephfs/share_916081/johntianlan/bert-base-chinese
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall
    en: /apdcephfs/share_916081/johntianlan/gpt2_english

# test configuration
test:
    seed: 0
    batch_size: 1
    prefix_length_rate: 0.5
