temperature: 1.0
# dynamic searching parameters (left windows position and right windows position)
# english 0, chinese 2
left_window_size: 0
right_window_size: 8
test_max_len: 128
prefix_len: 32
doc_max_length: 256
max_doc_num: 50
min_phrase_length: 2
max_phrase_length: 8
max_doc_length: 256
# the topk phrases that be considered
search_topk: 5
threshold: 20.
recall_topk: 100
# the max seqlength for calculating the phrase ppl
max_rerank_len: 128
phrase_alpha: 0.8
# dynamic update the docs
update_step: 128
# max query len for encoding SimCSE model
max_query_len: 512
contrastive_phrase_score_penalty: 100
coarse_score_alpha: 0.5
softmax_temp: 0.1

buffer_size: 40960

phrase_tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
phrase_encoder_model: 
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall
    en: /apdcephfs/share_916081/johntianlan/gpt2_english

# test configuration
test:
    seed: 0
    batch_size: 1
    prefix_length_rate: 0.5
