test_interval: 1.1
valid_during_training: false
is_step_for_training: true
total_step: 5010
test_max_len: 64
prefix_len: 32
topk: 8
topp: 0.93
max_len: 128
res_max_len: 32

# gpt2 configuration
test_max_len: 64
tokenizer: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
pretrained_model: 
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

# train configuration
train:
    load_param: true
    lr: 0.00002
    grad_clip: 1.0
    seed: 0
    batch_size: 64
    warmup_ratio: 0.
    iter_to_accumulate: 1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 256
