temp: 1.0
full_turn_length: 5
test_interval: 0.05
gray_cand_num: 2
valid_during_training: true

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 80
    max_len: 64
    res_max_len: 32
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: dual-bert/best_bert-base-chinese_0.pt
        # path: dual-bert/best_bert-base-uncased.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 128 
    max_len: 64
    ctx_max_len: 256
    topk: 20
    index_type: Flat
    index_nprobe: 1
    dimension: 768
