test_interval: 0.05
valid_during_training: true
nhead: 12
num_layers: 3
gray_cand_num: 3
before_comp: true
dropout: 0.1

# corrupt parameters
deletion_ratio: 0.3
deletion_min_num: 1
deletion_num: 1
concatention_num: 4

tokenizer:
    zh: /apdcephfs/share_733425/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_733425/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-fp-mono/best__apdcephfs_share_916081_johntianlan_bert-base-uncased_11.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 32
    ctx_max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
