#The model structure of the dual-bert-sp is the same as the dual-bert model, but the way of loading the pre-trained langauge models is different. For dual-bert-sp, the bert-fp-mono is loaded in response BERT encoder and bert-fp is loaded in context BERT encoder.
temp: 1.
full_turn_length: 5
test_interval: 0.01
valid_during_training: true

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 112
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-post/best_nspmlm.pt     # uselss parameter
        context_encoder_path: bert-fp-mono-plus/best_bert-base-chinese_10.pt
        # context_encoder_path: bert-post/best_nspmlm.pt
        # response_encoder_path: bert-fp-mono/best_bert-base-uncased.pt
        response_encoder_path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 128 
    max_len: 64
    ctx_max_len: 256
    topk: 20
    # index_type: IVF3722,Flat
    # index_type: IVF6509,Flat
    # index_type: IVF931,Flat
    index_type: Flat
    # index_type: LSH
    index_nprobe: 5
    dimension: 768
