# arxiv: 0; writer: 5
gray_cand_num: 5
test_interval: 0.1
valid_during_training: false

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 1.0
    seed: 0
    batch_size: 128
    max_len: 64
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

inference:
    seed: 50
    batch_size: 512
    max_len: 64
    index_type: LSH
    dimension: 768
    topk: 100
