test_interval: 0.05
valid_during_training: true

tokenizer:
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 10
    warmup_ratio: 0.
    checkpoint: 
        path: bert-fp-mono/best__apdcephfs_share_916081_johntianlan_bert-base-uncased_11.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

