temp: 0.05
full_turn_length: 5
test_interval: 0.05
valid_during_training: true
is_step_for_training: false
# rrs: 10000; douban: 30000; ecommerce: 45000
total_step: 45010
nhead: 12
num_layers: 2
dropout: 0.1
margin: 0.7
coarse_recall_loss: true
small_turn_size: 10
predict_ensemble: false

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-comp/best_bert-base-chinese.pt
        # path: bert-fp/best_bert-base-chinese.pt
        # path: bert-fp-mono/best_bert-base-chinese.pt
        path: bert-fp-mono/best__apdcephfs_share_916081_johntianlan_bert-base-chinese_709.pt
        # path: bert-fp-mono/best_bert-base-uncased.pt
        # path: dual-bert/best_bert-base-chinese_500.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 64
    ctx_max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
