test_interval: 0.01
valid_during_training: false
is_step_for_training: true
total_step: 40010
sample_ratio: 0.15

# gpt2 configuration
test_max_len: 128
tokenizer: 
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
pretrained_model: 
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
    zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 256
    warmup_ratio: 0.0
    iter_to_accumulate: 4
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 128
    max_len: 128
