test_interval: 0.05
valid_during_training: false
is_step_for_training: true
total_step: 500000
save_every: 20000
test_max_ctx_len: 512
num_beam: 5
sep_smooth_length: 50
prefix_len: 32
topk: 8
topp: 0.93
# contrastive search params
beam_width: 5
model_prediction_confidence: 0.4
contrastive_topk: 8
contrastive_topp: 0.93

# for dialog
res_max_len: 32
inference_num: 1

# gpt2 configuration
test_max_len: 32
tokenizer: 
    en: /apdcephfs/share_916081/johntianlan/bert-base-cased
pretrained_model: 
    en: /apdcephfs/share_916081/johntianlan/gpt2_english

# train configuration
train:
    load_param: true
    lr: 0.0001
    grad_clip: 0.1
    seed: 0
    batch_size: 32 
    max_len: 256
    warmup_ratio: 0.06
    iter_to_accumulate: 1
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: gpt2-original/best_wikitext103_ckpt.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 512

# infernece
inference:
    seed: 0
    batch_size: 128
    max_len: 128
