test_interval: 0.05
valid_during_training: false
is_step_for_training: true
total_step: 500000
save_every: 10000
test_max_ctx_len: 256
num_beam: 5
sep_smooth_length: 50
prefix_len: 32
topk: 8
topp: 0.93
# contrastive search params
beam_width: 5
model_prediction_confidence: 0.4
contrastive_topk: 8
contrastive_topp: 0.93

# for dialog
res_max_len: 32
inference_num: 1

# gpt2 configuration
test_max_len: 32
tokenizer: 
    # zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall
pretrained_model: 
    # zh: /apdcephfs/share_916081/johntianlan/gpt2_with_long_time
    en: /apdcephfs/share_916081/johntianlan/gpt2_english
    zh: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall

# train configuration
train:
    load_param: true
    lr: 0.0001
    grad_clip: 0.1
    seed: 0
    batch_size: 16
    max_len: 512
    warmup_ratio: 0.
    iter_to_accumulate: 1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 512

# infernece
inference:
    seed: 0
    batch_size: 128
    max_len: 128
