# hashing module parameters
hash_code_size: 256
hidden_size: 768
q_alpha: 0.001
q_alpha_max: 0.1
hash_loss_scale: 1
hash_loss_matrix_scale: 1
kl_loss_scale: 1


temp: 0.05
full_turn_length: 100
test_interval: 0.05
valid_during_training: true
max_turn_length: 16
mv_num: 5
queue_size: 10240
momentum_ratio: 0.999
upon_model: /apdcephfs/share_916081/johntianlan/gpt2-chinese-cluecorpussmall

# transformer layer
trs_hidden_size: 768
trs_nhead: 12
trs_nlayer: 3
dropout: 0.1

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 128
    max_len: 64
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: dual-bert-hier-trs/best__apdcephfs_share_916081_johntianlan_bert-base-chinese_701.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 32
    ctx_max_len: 64
    topk: 20
    index_type: IVF65536,Flat
    index_nprobe: 5
    dimension: 768
