poly_m: 128
test_interval: 0.05
full_turn_length: 5

tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
# pretrained_model:
#     zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
#     en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64
