valid_during_training: true
is_step_for_training: true
total_step: 50010
save_every: 10000
test_max_len: 64

# contrastive search parameters
beam_width: 3
model_prediction_confidence: 0.4
margin: 0.5
cl_loss_alpha: 1.
sampling_prefix_len: 1
contrastive_topk: 5
contrastive_topp: 0.6
sep_smooth_length: 1

# gpt2 configuration load locally
tokenizer: 
    # zh: /apdcephfs/share_733425/johntianlan/gpt2-l-300g
    zh: /apdcephfs/share_916081/johntianlan/gpt2-l-300g
    # en: /apdcephfs/share_733425/johntianlan/gpt2-large
    en: /apdcephfs/share_916081/johntianlan/gpt2-large
pretrained_model: 
    # zh: /apdcephfs/share_733425/johntianlan/gpt2-l-300g
    zh: /apdcephfs/share_916081/johntianlan/gpt2-l-300g
    # en: /apdcephfs/share_733425/johntianlan/gpt2-large
    en: /apdcephfs/share_916081/johntianlan/gpt2-large

# data_root_path: /apdcephfs/share_733425/johntianlan/english_common_crawl
# data_root_path: /apdcephfs/share_916081/johntianlan/english_common_crawl
data_root_path: /apdcephfs/share_916081/johntianlan/chinese_high_quality_300g
# data_root_path: /apdcephfs/share_733425/johntianlan/chinese_high_quality_300g
buffer_size: 409600

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 1.0
    seed: 0
    batch_size: 64 
    max_len: 256
    warmup_ratio: 0.05
    # iter_to_accumulate: 8
    iter_to_accumulate: 1
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        is_load: false

test:
    seed: 0
    batch_size: 1
    max_len: 256
    test_max_len: 256
