temp: 0.05
save_every: 500
max_len: 512

tokenizer:
    zh: bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    lr: 0.00001
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    res_max_len: 512
    epoch: 1
    warmup_ratio: 0.01
    checkpoint: 
        # path: bert-post/best_nspmlm.pt
        path: bert-fp-mono/best__apdcephfs_share_916081_johntianlan_bert-base-chinese_101.pt
        # path: bert-fp/best_bert-base-chinese.pt
        is_load: false

test:
    seed: 0
    batch_size: 1
    # index_type: IVF65536_HNSW32,PQ8
    index_type: IVF10000,Flat
    index_nprobe: 70
    dimension: 768

inference:
    seed: 0
    batch_size: 256
    max_len: 512
    topk: 20
    # index_type: IVF65536_HNSW32,PQ8
    # index_type: IVF10000,Flat
    # index_type: Flat
    index_type: IVF10000,Flat
    index_nprobe: 10
    dimension: 768
    min_test_len: 16
    min_test_context_len: 64
