temp: 0.05

# train configuration
train:
    lr: 0.00001
    grad_clip: 1.0
    seed: 0
    batch_size: 16
    res_max_len: 512
    epoch: 1
    warmup_ratio: 0.01
    checkpoint: 
        path: bert-post/best_nspmlm.pt
        # path: bert-fp/best_bert-base-chinese.pt
        is_load: false

test:
    seed: 0
    batch_size: 1

inference:
    seed: 0
    batch_size: 128
    max_len: 512
    topk: 20
    index_type: IVF65536_HNSW32,Flat
    index_nprobe: 1
    dimension: 768
    min_test_len: 16
    min_test_context_len: 64
