valid_during_training: false
test_interval: 0.001
gru_hidden: 300

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_uttr_len: 50
    max_uttr_num: 10
    neg_candi_num: 5
    res_max_len: 64
    margin: 0.2
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: false

# test configuration
test:
    seed: 0
    max_uttr_len: 50
    max_uttr_num: 10
    batch_size: 2
    max_len: 256
    res_max_len: 64

# inference configuration
inference:
    seed: 0
    batch_size: 256
    max_len: 32
    ctx_max_len: 64
    topk: 20
    index_type: Flat
    index_nprobe: 5
    dimension: 768
