temp: 0.05
full_turn_length: 5
test_interval: 0.05
valid_during_training: true
max_turn_length: 16
mv_num: 5
work_topk: 2000
human_work_topk: 5
max_turn_num: 8
# max_memory_size: 100
max_memory_size: 10000

# transformer layer
trs_hidden_size: 768
trs_nhead: 12
trs_nlayer: 3
dropout: 0.1

# network issue, load locally
tokenizer:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased
pretrained_model:
    zh: /apdcephfs/share_916081/johntianlan/bert-base-chinese
    en: /apdcephfs/share_916081/johntianlan/bert-base-uncased

# train configuration
train:
    load_param: true
    lr: 0.00005
    grad_clip: 5.0
    seed: 0
    batch_size: 64
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    checkpoint: 
        path: bert-fp-mono/best_bert-base-chinese.pt
        is_load: false

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 32
    index_type: IVF10000,Flat
    index_nprobe: 50
    dimension: 768

# inference configuration
inference:
    seed: 0
    batch_size: 512
    max_len: 64
    ctx_max_len: 256
    topk: 10
    index_type: Flat
    index_nprobe: 5
    dimension: 768
