test_interval: 0.01
# bigger than 1 means not swap
swap_interval: 1.1
valid_during_training: false
gray_cand_num: 10

# train configuration
train:
    inner_bsz: 64
    load_param: true
    lr: 0.00003
    grad_clip: 5.0
    seed: 0
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    training_model: bi-encoder
    bi_encoder: dual-bert
    cross_encoder: sa-bert
    checkpoint: 
        bi_encoder: dual-bert/best_bert-base-chinese_0.pt
        cross_encoder: sa-bert/best_bert-base-chinese_0.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64
