test_interval: 0.01
temp: 0.07
valid_during_training: false
gray_cand_num: 10
detect_margin: 0.4
training_hard_margin: 0.05
training_easy_margin: 0.1
# bigger than 1 means not swaping 
swap_interval: 1.1

# train configuration
train:
    inner_bsz: 64
    load_param: true
    lr: 0.00005
    grad_clip: 1.0
    seed: 1
    batch_size: 32
    max_len: 256
    res_max_len: 64
    epoch: 5
    warmup_ratio: 0.
    training_model: bi-encoder
    bi_encoder: dual-bert
    cross_encoder: sa-bert
    checkpoint: 
        bi_encoder: dual-bert/best_bert-base-chinese_0.pt
        cross_encoder: sa-bert/best_bert-base-chinese_0.pt
        is_load: true

# test configuration
test:
    seed: 0
    batch_size: 1
    max_len: 256
    res_max_len: 64
